/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MainApp {
    }
    interface StencilTest {
        "hideDefaultSlot"?: boolean;
        "hideSuffixSlot"?: boolean;
        "wrapper"?: 'span' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'pre' | 'strong' | 'em';
    }
}
declare global {
    interface HTMLMainAppElement extends Components.MainApp, HTMLStencilElement {
    }
    var HTMLMainAppElement: {
        prototype: HTMLMainAppElement;
        new (): HTMLMainAppElement;
    };
    interface HTMLStencilTestElement extends Components.StencilTest, HTMLStencilElement {
    }
    var HTMLStencilTestElement: {
        prototype: HTMLStencilTestElement;
        new (): HTMLStencilTestElement;
    };
    interface HTMLElementTagNameMap {
        "main-app": HTMLMainAppElement;
        "stencil-test": HTMLStencilTestElement;
    }
}
declare namespace LocalJSX {
    interface MainApp {
    }
    interface StencilTest {
        "hideDefaultSlot"?: boolean;
        "hideSuffixSlot"?: boolean;
        "wrapper"?: 'span' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'pre' | 'strong' | 'em';
    }
    interface IntrinsicElements {
        "main-app": MainApp;
        "stencil-test": StencilTest;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "main-app": LocalJSX.MainApp & JSXBase.HTMLAttributes<HTMLMainAppElement>;
            "stencil-test": LocalJSX.StencilTest & JSXBase.HTMLAttributes<HTMLStencilTestElement>;
        }
    }
}
